backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog Posts'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Preview Image', name: 'image', widget: 'image' }

  - name: 'notice'
    label: 'Notices'
    folder: 'content/notices'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'inlinemessage'
    label: 'Inline Messages'
    folder: 'content/inlinemessages'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Identifier', name: 'id', widget: string }

  - name: 'picturemessage'
    label: 'Picture Messages'
    folder: 'content/picturemessages'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Identifier', name: 'id', widget: string }

  - name: 'heroimages'
    label: 'Hero Images'
    folder: 'content/heroimages'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Image', name: 'image', widget: 'image' }

  - name: 'sutras'
    label: 'Sutras'
    folder: 'content/sutras'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{en-title}}'
    editor:
      preview: false
    fields:
      - { label: 'English Title', name: 'enTitle', widget: 'string' }
      - { label: 'Vietnamese Title', name: 'viTitle', widget: 'string' }
      - { label: 'English Text', name: 'enText', widget: 'markdown' }
      - { label: 'Vietnamese Text', name: 'viText', widget: 'markdown' }
      - { label: 'Identifier', name: 'id', widget: string }
