backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

i18n:
  structure: multiple_folders
  locales: [en, vi]
  default_locale: en

collections:
  - name: 'blog'
    label: 'Blog Posts'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Preview Image', name: 'image', widget: 'image' }

  - name: 'quotemessage'
    label: 'Quote Messages'
    folder: 'content/quotemessages'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: '{{year}}-{{month}}-{{day}}-{{id}}'
    fields:
      - { label: 'Author', name: 'author', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'Identifier', name: 'id', widget: 'string', i18n: 'duplicate' }

  - name: 'inlinemessage'
    label: 'Inline Messages'
    folder: 'content/inlinemessages'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'Identifier', name: 'id', widget: 'string', i18n: 'duplicate' }

  - name: 'picturemessage'
    label: 'Picture Messages'
    folder: 'content/picturemessages'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'Image', name: 'image', widget: 'image', i18n: 'duplicate' }
      - { label: 'Identifier', name: 'id', widget: 'string', i18n: 'duplicate' }

  - name: 'heroimages'
    label: 'Hero Images'
    folder: 'content/heroimages'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Identifier', name: 'id', widget: 'string' }

  - name: 'sutras'
    label: 'Sutras'
    folder: 'content/sutras'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
      - { label: 'Identifier', name: 'id', widget: string, i18n: 'duplicate' }
